export const credits = [
	{
		id: 'planet-earth',
		title: 'Planet Earth',
		type: '3D Model',
		modelUrl: 'https://skfb.ly/owwQH',
		artist: 'JanesBT',
		license: 'Creative Commons Attribution',
		licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
		licenseBadge: 'CC BY 4.0',
	},
	{
		id: 'mercury',
		title: 'Mercury',
		type: '3D Model',
		modelUrl: 'https://skfb.ly/6TwFJ',
		artist: 'Akshat',
		license: 'Creative Commons Attribution',
		licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
		licenseBadge: 'CC BY 4.0',
	},
	{
		id: 'venus',
		title: 'Venus',
		type: '3D Model',
		modelUrl: 'https://skfb.ly/ITvT',
		artist: 'kongle',
		license: 'Creative Commons Attribution-ShareAlike',
		licenseUrl: 'http://creativecommons.org/licenses/by-sa/4.0/',
		licenseBadge: 'CC BY-SA 4.0',
	},
	{
		id: 'mars',
		title: 'Mars',
		type: '3D Model',
		modelUrl: 'https://skfb.ly/6Uynr',
		artist: 'AirStudios',
		license: 'Creative Commons Attribution',
		licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
		licenseBadge: 'CC BY 4.0',
	},
	{
		id: 'jupiter',
		title: 'Jupiter',
		type: '3D Model',
		modelUrl: 'https://skfb.ly/6TwHq',
		artist: 'Akshat',
		license: 'Creative Commons Attribution',
		licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
		licenseBadge: 'CC BY 4.0',
	},
	{
		id: 'saturn',
		title: 'Saturn',
		type: '3D Model',
		modelUrl: 'https://skfb.ly/6TwHZ',
		artist: 'Akshat',
		license: 'Creative Commons Attribution',
		licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
		licenseBadge: 'CC BY 4.0',
	},
	{
		id: 'uranus',
		title: 'Uranus',
		type: '3D Model',
		modelUrl: 'https://skfb.ly/pqrEK',
		artist: 'Nestaeric',
		license: 'Creative Commons Attribution',
		licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
		licenseBadge: 'CC BY 4.0',
	},
	{
		id: 'neptune',
		title: 'Neptune',
		type: '3D Model',
		modelUrl: 'https://skfb.ly/pDAHv',
		artist: 'Nestaeric',
		license: 'Creative Commons Attribution',
		licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
		licenseBadge: 'CC BY 4.0',
	},
	{
		id: 'pluto',
		title: 'Pluto',
		type: '3D Model',
		modelUrl: 'https://skfb.ly/6U8FR',
		artist: 'PatelDev',
		license: 'Creative Commons Attribution',
		licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
		licenseBadge: 'CC BY 4.0',
	},
	{
		id: 'black-hole',
		title: 'Black Hole',
		type: '3D Model',
		modelUrl: 'https://skfb.ly/pq8CF',
		artist: 'Nestaeric',
		license: 'Creative Commons Attribution',
		licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
		licenseBadge: 'CC BY 4.0',
	},
];
